In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

project_root = Path.cwd().resolve()

while (
    not (
        project_root
        / "data/processed/quality_reports/field_types.csv"
    ).is_file()
    and project_root != project_root.parent
):
    project_root = project_root.parent

schema_path = (
    project_root
    / "data/processed/quality_reports/field_types.csv"
)

if not schema_path.is_file():
    raise FileNotFoundError("Run this notebook from inside the project.")

field_types = pd.read_csv(schema_path, dtype="string")

display(field_types)

               dataset                field pandas_dtype
0    competitor_master             brand_id       string
1    competitor_master           brand_name       string
2    competitor_master        operator_name       string
3    competitor_master      comparison_role       string
4    competitor_master     primary_category       string
..                 ...                  ...          ...
222    source_register       evidence_basis       string
223    source_register  verification_status       string
224    source_register        access_status       string
225    source_register    historical_period       string
226    source_register                notes       string

[227 rows x 3 columns]

In [2]:
for dataset_name in field_types["dataset"].drop_duplicates():
    print("\nTable:", dataset_name)

    display(
        field_types.loc[
            field_types["dataset"].eq(dataset_name),
            ["field", "pandas_dtype"]
        ].reset_index(drop=True)
    )

Table: competitor_master

                              field    pandas_dtype
0                          brand_id          string
1                        brand_name          string
2                     operator_name          string
3                   comparison_role          string
4                  primary_category          string
5               customer_competitor          string
6   franchise_investment_competitor          string
7                  official_website          string
8              global_founding_year           Int64
9                     ph_start_year           Int64
10                price_positioning          string
11              ph_franchise_status          string
12              geographic_coverage          string
13                       source_ids          string
14              verification_status          string
15                 inclusion_status          string
16                 inclusion_reason          string
17               last_verified_date  datetime64[us]
18                            notes          string

Table: branch_directory

                  field    pandas_dtype
0             branch_id          string
1              brand_id          string
2           branch_name          string
3               address          string
4                  city          string
5              province          string
6                region          string
7          island_group          string
8          store_format          string
9      operating_status          string
10          status_date   datetime64[s]
11        observed_date  datetime64[us]
12           source_ids          string
13  verification_status          string
14                notes          string

Table: menu_pricing

                      field    pandas_dtype
0            observation_id          string
1                  brand_id          string
2                 branch_id          string
3                 source_id          string
4             observed_date  datetime64[us]
5                   channel          string
6            location_scope          string
7              product_name          string
8          product_category          string
9          comparison_group          string
10              temperature          string
11               size_label          string
12                volume_ml         Float64
13        regular_price_php         Float64
14          promo_price_php         Float64
15      availability_status          string
16                    notes          string
17      displayed_price_php         Float64
18              price_basis          string
19   published_menu_section          string
20      product_description          string
21  size_label_standardised          string

Table: promotions

                   field    pandas_dtype
0           promotion_id          string
1               brand_id          string
2              branch_id          string
3              source_id          string
4          observed_date  datetime64[us]
5             offer_name          string
6             offer_type          string
7              mechanics          string
8            eligibility          string
9             start_date  datetime64[us]
10              end_date  datetime64[us]
11               channel          string
12        location_scope          string
13     minimum_spend_php         Float64
14        discount_value         Float64
15         discount_unit          string
16  maximum_discount_php         Float64
17      redemption_limit           Int64
18            exclusions          string
19   availability_status          string
20                 notes          string

Table: loyalty_programs

                 field    pandas_dtype
0   program_version_id          string
1             brand_id          string
2            source_id          string
3        observed_date  datetime64[us]
4         program_name          string
5       effective_date   datetime64[s]
6     enrollment_rules          string
7        earning_rules          string
8     redemption_rules          string
9         expiry_rules          string
10          tier_rules          string
11            benefits          string
12             channel          string
13      location_scope          string
14          exclusions          string
15               notes          string

Table: store_assessments

                        field    pandas_dtype
0               assessment_id          string
1                    brand_id          string
2                   branch_id          string
3                   source_id          string
4               observed_date  datetime64[us]
5          observation_method          string
6                  visit_time          string
7                store_format          string
8          design_description          string
9         seating_description          string
10        comfort_description          string
11                wifi_status          string
12        power_outlet_status          string
13  accessibility_description          string
14             service_layout          string
15          queue_description          string
16        service_start_event          string
17          service_end_event          string
18       service_time_minutes         Float64
19           visit_conditions          string
20                      notes          string

Table: customer_reviews

               field    pandas_dtype
0          review_id          string
1          sample_id          string
2           brand_id          string
3          branch_id          string
4          source_id          string
5           platform          string
6       review_scope          string
7        review_date   datetime64[s]
8     collected_date  datetime64[us]
9             rating         Float64
10  rating_scale_max         Float64
11       review_text          string
12        text_basis          string
13          language          string
14  company_selected          string
15             notes          string

Table: ordering_channels

                     field    pandas_dtype
0   channel_observation_id          string
1                 brand_id          string
2                branch_id          string
3                source_id          string
4            observed_date  datetime64[us]
5                  channel          string
6            ordering_mode          string
7           location_scope          string
8            access_method          string
9      availability_status          string
10          ordering_steps          string
11   customization_options          string
12         payment_options          string
13       minimum_order_php         Float64
14        delivery_fee_php         Float64
15         other_fee_terms          string
16       delivery_coverage          string
17     quoted_wait_minutes         Float64
18       checkout_verified          string
19                   notes          string

Table: franchise_offers

                           field    pandas_dtype
0             package_version_id          string
1                       brand_id          string
2                      source_id          string
3                  observed_date  datetime64[us]
4                 effective_date   datetime64[s]
5                   package_name          string
6                   market_scope          string
7                   store_format          string
8                       currency          string
9           total_investment_min         Float64
10          total_investment_max         Float64
11                 franchise_fee         Float64
12         investment_inclusions          string
13         investment_exclusions          string
14                     tax_basis          string
15                 royalty_terms          string
16           marketing_fee_terms          string
17          other_recurring_fees          string
18                agreement_term          string
19                 renewal_terms          string
20            space_requirements          string
21              training_support          string
22           operational_support          string
23            supply_obligations          string
24           availability_status          string
25                         notes          string
26  advertised_package_start_php         Float64

Table: commercial_developments

               field    pandas_dtype
0     development_id          string
1           brand_id          string
2          source_id          string
3      observed_date  datetime64[us]
4     published_date   datetime64[s]
5     effective_date   datetime64[s]
6   development_type          string
7         offer_name          string
8        description          string
9    target_customer          string
10           channel          string
11    location_scope          string
12  commercial_terms          string
13    evidence_basis          string
14             notes          string

Table: event_packages

                   field    pandas_dtype
0       event_package_id          string
1               brand_id          string
2         development_id          string
3              source_id          string
4          observed_date  datetime64[us]
5         effective_date   datetime64[s]
6           package_name          string
7         service_method          string
8                    pax           Int64
9          included_cups           Int64
10        cup_size_label          string
11         service_hours         Float64
12  advertised_price_php         Float64
13           tax_wording          string
14        location_scope          string
15            inclusions          string
16      additional_costs          string
17           source_page           Int64
18                 notes          string

Table: source_register

                    field    pandas_dtype
0               source_id          string
1                brand_id          string
2               branch_id          string
3   research_question_ids          string
4             source_type          string
5            source_title          string
6              source_url          string
7          published_date  datetime64[us]
8          effective_date   datetime64[s]
9          collected_date  datetime64[us]
10          evidence_file          string
11         evidence_basis          string
12    verification_status          string
13          access_status          string
14      historical_period          string
15                  notes          string

In [3]:
review_sampling = pd.read_csv(
    project_root / "references/review_sampling.csv",
    dtype="string"
)

print("Review sampling fields:")
print(review_sampling.columns.tolist())

display(review_sampling.head())

print("Sampling records:", len(review_sampling))
print(
    "Duplicate sample IDs:",
    review_sampling["sample_id"].duplicated().sum()
)

Review sampling fields:
['sample_id', 'brand_id', 'branch_id', 'platform', 'review_scope', 'source_id', 'window_start', 'window_end', 'selection_method', 'sort_order', 'search_query', 'target_count', 'available_count', 'collected_count', 'collected_at', 'access_status', 'limitations']

,sample_id,brand_id,branch_id,platform,review_scope,source_id,window_start,window_end,selection_method,sort_order,search_query,target_count,available_count,collected_count,collected_at,access_status,limitations
0,SMP0001,BFC006,BRN0001,Google,Branch,<NA>,2025-10-24,2026-10-23,Purposive branch selection; up to 30 newest el...,Newest first where available; otherwise docume...,<NA>,30,<NA>,0,<NA>,Not attempted,Planning record only. Confirm platform listing...
1,SMP0002,BFC006,BRN0001,Foodpanda,Branch,<NA>,2025-10-24,2026-10-23,Purposive branch selection; up to 30 newest el...,Newest first where available; otherwise docume...,<NA>,30,<NA>,0,<NA>,Not attempted,Planning record only. Confirm platform listing...
2,SMP0003,BFC006,BRN0001,Grab,Branch,<NA>,2025-10-24,2026-10-23,Purposive branch selection; up to 30 newest el...,Newest first where available; otherwise docume...,<NA>,30,<NA>,0,<NA>,Not attempted,Planning record only. Confirm platform listing...
3,SMP0004,BFC006,BRN0002,Google,Branch,<NA>,2025-10-24,2026-10-23,Purposive branch selection; up to 30 newest el...,Newest first where available; otherwise docume...,<NA>,30,<NA>,0,<NA>,Not attempted,Planning record only. Confirm platform listing...
4,SMP0005,BFC006,BRN0002,Foodpanda,Branch,<NA>,2025-10-24,2026-10-23,Purposive branch selection; up to 30 newest el...,Newest first where available; otherwise docume...,<NA>,30,<NA>,0,<NA>,Not attempted,Planning record only. Confirm platform listing...

Sampling records: 75
Duplicate sample IDs: 0